server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;
  root   /usr/share/nginx/html;

  location / {
    expires max;
    try_files $uri $uri/ /index.html;
  }

  location = /index.html {
    expires -1;
  }

  error_page   500 502 503 504  /50x.html;

  gzip on;
  gzip_min_length 1k;
  gzip_comp_level 4;
  gzip_types text/plain application/json application/javascript image/png image/jpeg image/jpg image/gif;
  gzip_vary on;
  gzip_disable "MSIE [1-6]\.";
}